# Generated by Django 3.2.6 on 2021-08-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_question_question_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_rate',
            field=models.FloatField(),
        ),
    ]
